### ISSUE TITLE
Tome status

### ISSUE THREAD

**Issue by WeeskyBDW** [Njol/Tome-compiler#1]
Hello, Tome langage can be use ? (If i compile the code) You have exemple How to develop in Tome?

**Comment by Njol** [comment]
If you're lucky you might be able to test a first buggy version in 5 to 10 years 😀

I'm not kidding, creating a new language from scratch with even just some basic tools takes much more time than I have anticipated.

**Comment by WeeskyBDW** [comment]
Re.
Do you have idea what can be syntax of tome ? Like skript syntax ? Like java syntax ?

**Comment by XfedeX** [comment]
I'm curious too!

**Comment by Njol** [comment]
The syntax is probably some mix between Java and Rust. But I've pretty much given up on this project, since I've been working on it on and off for years now and it's going nowhere. Making a general-purpose programming language from scratch with all the tooling required (even just the compiler & IDE integration) is much more work than anticipated. I think I'll just switch to Rust instead of trying to make something similar.
